### ISSUE TITLE
Version 3.10.8 is not starting a wizard

### ISSUE THREAD

**Issue by jbruchanov** [pducharme/UniFi-Video-Controller#158] opened 2019-09-26 20:35 UTC
Trying to run on Synology DS918+ (DSM 6.2.2-24922 Update 3)

running 
```
docker run --name unifi-video-latest --cap-add SYS_ADMIN --cap-add DAC_READ_SEARCH -p 10001:10001 -p 1935:1935 -p 6666:6666 -p 7080:7080 -p 7442:7442 -p 7443:7443 -p 7444:7444 -p 7445:7445 -p 7446:7446 -p 7447:7447 -v /volume1/docker/unifi-video-latest:/var/lib/unifi-video -v /volume1/docker/unifi-video-latest/videos:/var/lib/unifi-video/videos -e TZ=Europe/London -e PUID=1028 -e PGID=100 -e DEBUG=1 --security-opt apparmor:unconfined pducharme/unifi-video-controller:latest
```
PUID=1028 is valid value for my docker account, 
data folders are created and docker user as set as the owner

Executing it fails `Service exit with a return value of 5`
Starting it again and opening https://web:7443/ (not port 7080, it never worked for me) stays few moments on "Update database" screen and then I can see a login screen.
However I can't login with `ubnt`/`ubnt` (I would expect to have a wizard though as it's fresh data folder, not an update).

I tried to add `is_default=true` into `/system.properties` and restart. It doesn't help unfortunatelly and ends again with the 'Service exit with a return value of 5'.
`system.properties` is though updated by it and it's empty again.

Attaching logs from synology docker.

Any ideas what might be wrong ?
Using version 3.10.6 works fine
[unifi-video-latest.csv.txt](https://github.com/pducharme/UniFi-Video-Controller/files/3659783/unifi-video-latest.csv.txt)

**Comment by fryfrog** [comment] 2019-09-27 00:28
There is a tag for `3.10.6`, does that work?

**Comment by jbruchanov** [comment] 2019-09-27 09:18
3.10.6 works fine...
3.10.8 seems to have some issue during first initialisation/wizard

**Comment by ChadOhman** [comment] 2019-09-28 05:38
Adding to this.. starting on 3.10.6 works however upgrading to :latest prevents me from logging in with the configuration I created on 3.10.6.

**Comment by fryfrog** [comment] 2019-09-28 14:24
God I hate Ubiquiti's whole treatment of upgrades. It'll take me a bit to figure out what is going on, obviously you should use `:3.10.6` until then.

**Comment by coalfield** [comment] 2019-09-28 19:27
I have a fresh install of 3.10.8 and can confirm this is showing a L/P prompt on a fresh install (with nothing prior, unable to login with defaults and have never set up the container so would have nothing else to use

**Comment by grantmacnamara** [comment] 2019-09-30 12:31
Yup, same issue. I can see that system.properties is being overwritten or cleared when starting up.

**Comment by sfinlon** [comment] 2019-10-01 17:04
> God I hate Ubiquiti's whole treatment of upgrades. It'll take me a bit to figure out what is going on, obviously you should use `:3.10.6` until then.

It looks like it's an issue invoking some Google module... I haven't looked at Ubiquiti's build dock for 3.10.8 but this is what fails.

`10/1/2019 1:02:30 PM.java.lang.reflect.InvocationTargetException
10/1/2019 1:02:30 PM	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10/1/2019 1:02:30 PM	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10/1/2019 1:02:30 PM	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10/1/2019 1:02:30 PM	at java.lang.reflect.Method.invoke(Method.java:498)
10/1/2019 1:02:30 PM	at org.apache.commons.daemon.support.DaemonLoader.start(DaemonLoader.java:243)
10/1/2019 1:02:30 PMCaused by: com.google.inject.CreationException: Guice creation errors:
10/1/2019 1:02:30 PM
10/1/2019 1:02:30 PM1) Error injecting constructor, java.lang.NullPointerException
10/1/2019 1:02:30 PM  at com.ubnt.airvision.system.SystemConfiguration.<init>(Unknown Source)
10/1/2019 1:02:30 PM  at com.ubnt.airvision.A.String.configure(Unknown Source)
10/1/2019 1:02:30 PM  while locating com.ubnt.airvision.system.SystemConfiguration
10/1/2019 1:02:30 PM
10/1/2019 1:02:30 PM1 error
10/1/2019 1:02:30 PM	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
10/1/2019 1:02:30 PM	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:183)
10/1/2019 1:02:30 PM	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
10/1/2019 1:02:30 PM	at com.google.inject.Guice.createInjector(Guice.java:95)
10/1/2019 1:02:30 PM	at com.google.inject.Guice.createInjector(Guice.java:72)
10/1/2019 1:02:30 PM	at com.google.inject.Guice.createInjector(Guice.java:62)
10/1/2019 1:02:30 PM	at com.ubnt.airvision.Main.getInjector(Unknown Source)
10/1/2019 1:02:30 PM	at com.ubnt.airvision.Main.initializeApp(Unknown Source)
10/1/2019 1:02:30 PM	at com.ubnt.airvision.Main.start(Unknown Source)
10/1/2019 1:02:30 PM	... 5 more
10/1/2019 1:02:30 PMCaused by: java.lang.NullPointerException
10/1/2019 1:02:30 PM	at com.ubnt.common.ooOO.A.super(Unknown Source)
10/1/2019 1:02:30 PM	at com.ubnt.airvision.system.SystemConfiguration.o00000(Unknown Source)
10/1/2019 1:02:30 PM	at com.ubnt.airvision.system.SystemConfiguration.<init>(Unknown Source)
10/1/2019 1:02:30 PM	at com.ubnt.airvision.system.SystemConfiguration$$FastClassByGuice$$90dc632.newInstance(<generated>)
10/1/2019 1:02:30 PM	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
10/1/2019 1:02:30 PM	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:60)
10/1/2019 1:02:30 PM	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
10/1/2019 1:02:30 PM	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
10/1/2019 1:02:30 PM	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
10/1/2019 1:02:30 PM	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
10/1/2019 1:02:30 PM	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
10/1/2019 1:02:30 PM	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
10/1/2019 1:02:30 PM	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
10/1/2019 1:02:30 PM	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:204)
10/1/2019 1:02:30 PM	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:198)
10/1/2019 1:02:30 PM	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
10/1/2019 1:02:30 PM	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:198)
10/1/2019 1:02:30 PM	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:179)
10/1/2019 1:02:30 PM	... 12 more
10/1/2019 1:02:30 PMCannot start daemon
10/1/2019 1:02:30 PMjava_start failed
10/1/2019 1:02:30 PMService exit with a return value of 5`

**Comment by ChadOhman** [comment] 2019-10-01 17:06
> some Google module

Kind of an aside, what and why is Ubiquiti using a Google module?

**Comment by fryfrog** [comment] 2019-10-02 18:20
I fired up a clean VM and get the same as you guys when I use `:latest`. I can drop to `:3.10.6` and run the wizard, log in, log out and then log back in again. Everything is fine still. Stop it and let it upgrade to `:latest` again w/ the db from a successful 3.10.6 initialization... and I can't log in. :/

**Comment by fryfrog** [comment] 2019-10-02 18:24
Well shit, here we go...

From 3.10.8:
`bin/mongod --config /usr/lib/unifi-video/conf/mongodv3.0+.conf`

From 3.10.6:
`bin/mongod --config /usr/lib/unifi-video/conf/mongod-wt.conf`

For some reason, it is going *back* to the *not* wired tiger database. What. The. Shit.

**Comment by kl4ng3r** [comment] 2019-10-03 21:43
Ditto. I can confirm the same problem on my end.
To make matters worse 3.10.8 seems to have updated the firmware on my cameras and when I roll back to 3.10.6, none of my cameras want to connect.
I've tried falling back to 3.10.6 - but get firmware mismatch (between camera and video software)

**Comment by Aggravate** [comment] 2019-10-04 17:22
I am having the same problem now, had one camera not getting adopted so I thought, maybe try the new version ... well now I am stuck between _cant login_ and _firmware mismatch_.

What do you think is the solution, just wait for 3.10.9+ or will a new docker container help?

thanks and greetings

**Comment by fryfrog** [comment] 2019-10-04 17:30
I think you can do one of two things to fix your current situation.

If you want to use 3.10.8, we need to figure out how to make sure it uses the wired tiger database instead of the old one. *My* personal one does this, but I suspect it is because I use MongoDB 4.x. I could walk the beta branch up to 3.6 and 4.0 and provide `:tags` to gradually upgrade, see if that helps. But if your DB isn't already wired tiger, you'd need to convert it.

You could also go back to 3.10.6 and manually downgrade the firmware on your camera(s).

**Comment by fryfrog** [comment] 2019-10-04 17:31
Can each of you with issues `docker exec` into your unifi-video container while running 3.10.6 and then 3.10.8 and do a `ps aux | grep mongo` and show the output of both here? That should make it clear if you're using wt or not.

**Comment by fryfrog** [comment] 2019-10-04 17:45
Okay, on *beta* I have pushed a commit that updates MongoDB to 3.6 and another to 4.0. And I've pushed tags for it, `:3.10.8-3.6` and `3.10.8-4.0`, though I don't know if they'll get processed properly. Keep an eye on the builds at https://hub.docker.com/r/pducharme/unifi-video-controller/builds

**Comment by kl4ng3r** [comment] 2019-10-04 18:07
thank you for that @fryfrog 

I went back further to 3.10.5, as that was my original deployment, still had firmware issues. 
And then pulled down your latest BETA build and now I can re-manage all my cameras :D :D :D yaaaay ! :) 

Thank you very much for doing that

**Comment by fryfrog** [comment] 2019-10-04 18:09
Wow, nice. I wonder if you got the build that had 3.6. Can you exec in and do the `ps`?

**Comment by kl4ng3r** [comment] 2019-10-04 18:53
unifi-v+   204  0.2  0.1 1125920 69040 ?       Sl   13:02   0:08 bin/mongod --config /usr/lib/unifi-video/conf/mongod-wt.conf

**Comment by fryfrog** [comment] 2019-10-04 18:54
Well, at least it did exactly as expected!

**Comment by kl4ng3r** [comment] 2019-10-04 18:55
@fryfrog Love your work Sir. So happy my system is back online.
I didn't have anything in the database, so not sure what other users will experience, but im happy I dont have to climb a ladder and reset all the cameras :)

**Comment by fryfrog** [comment] 2019-10-04 18:55
You wouldn't have had to do that, you can just go right to the web interface on a camera, log in and force download an *old* firmware version! :)

**Comment by kl4ng3r** [comment] 2019-10-04 18:58
So the problem I had is ... for some reason, the password that got pushed out to the cameras wasn't what I set it to be on the 3.10.5 controller. So when the controller went down I couldn't access the cameras individually. Couldn't ssh, web ... the only way was to reset or wait for controller 3.10.8 software to work, or a new docker version to be released.

Lucky I saved the password files from my data directory on 3.10.5 and I've been using those file to get access to the cameras on other container versions. Still can't SSH though. So my next task is going to be to reset passwords on cameras to something that I know works ;)

**Comment by Aggravate** [comment] 2019-10-05 09:48
> Okay, on `:beta` I have pushed a commit that updates MongoDB to 3.6 and another to 4.0. And I've pushed tags for it, `:3.10.8-3.6` and `:3.10.8-4.0`, though I don't know if they'll get processed properly. Keep an eye on the builds at https://hub.docker.com/r/pducharme/unifi-video-controller/builds

If I use the :beta tag, I have version 3.10.8 running and can login + Cameras are working!

Thank you very much!

**Comment by byteslip** [comment] 2019-10-05 12:28
Rookie here, having same problem. 

Build a new NAS on a Synology 918+. Running through Docker. The first version I tried was latest (3.10.8.) I'm having trouble trying to go back to 3.10.6, running the start in ssh, it constantly wants to go to and download the latest. 

Where can I comment out the command that is doing that?

**Comment by kl4ng3r** [comment] 2019-10-06 16:19
Sounds like you're starting up your old docker container every time.
Stop it. Delete it. And then instantiate a new one.

**Comment by jaeti01** [comment] 2019-10-06 18:01
Can you please help me getting the container back up and running? I am still having the problem signing back in. Tried tags 3.10.6 and beta as well. In the past I used to upgrade by emptying the data folder (except videos) and then updating the image, starting with an empty data folder and importing my backup. For some reason the controller asks for a username/password, even when I start with an empty data folder. Is that still the right procedure? thanks a lot! Till

**Comment by jaeti01** [comment] 2019-10-06 19:15
So, actually I got back online by reverting back to 3.10.5 which has the wizard and imported my backup and scanned the video folder. 
Should I now be able to apply the beta image without removing the data folder?

**Comment by fryfrog** [comment] 2019-10-07 16:26
In your running `:3.10.5` container, `docker exec` in and `ps aux | grep mongo` and show me what it is running. If mentions `-wt` for WiredTiger, I'd try going to `:3.10.6` and see if it works.

**Comment by fryfrog** [comment] 2019-10-07 16:46
The tags w/ `-` in their name didn't work, so I made them `:3.10.8.3.6` (which finished and proves it works) and `:3.10.8.4.0`. I would walk forward like `:3.10.6`, confirm it works. Then `:3.10.8.3.6` and confirm it works, then to `:3.10.8.4.0` and confirm it works.

**Comment by jaeti01** [comment] 2019-10-07 19:28
> In your running :3.10.5 container, docker exec in and ps aux | grep mongo and show me what it is running. If mentions -wt for WiredTiger, I'd try going to :3.10.6 and see if it works.

`unifi-v+   139  1.8  0.8 963520 66912 ?        Sl   21:21   0:01 bin/mongod --config /usr/lib/unifi-video/conf/mongodv3.0+.conf`

Hmm. Doesn't look like wt.
Does 3.10.6 have the broken wizard as well? Otherwise I can again backup, remove data, run 3.10.6 and import?

**Comment by fryfrog** [comment] 2019-10-07 19:52
I'm not sure what controls weather it starts up w/ the old db or new db style, it could be the version of monogodb? You could spin up a clean `:3.10.6` and see what it starts as. Or now start up a clean `:3.10.8.4.0` and see what it does. Actually, let *me* try that on my VM. :)

**Comment by fryfrog** [comment] 2019-10-07 19:55
When I fire up 3.10.8.4.0, I can log in w/ the old l/p I set, so I bet the wizard works. Trying that now.

**Comment by fryfrog** [comment] 2019-10-07 19:59
No... :(

**Comment by fryfrog** [comment] 2019-10-07 20:05
Okay, so what *does* work for me is start up w/ `:3.10.6` and do the wizard, then stop it and start up with `:beta` and it just works.

**Comment by byteslip** [comment] 2019-10-09 02:23
I rolled back to 3.10.5, created my account, stopped and deleted container, removed the ":3.10.5" from the last line, and boom running 3.10.8

**Comment by fryfrog** [comment] 2019-10-09 02:32
Humm, you didn't even have to use `:beta`?

**Comment by jaeti01** [comment] 2019-10-09 12:27
So I managed to get it working as well.
 My upgrade procedure to 3.10.8:
* create a fresh docker with 3.10.6 and a new data folder
    * create a temp user
    * stop and remove container
* start 3.10.8-beta on same data folder and with original video folder
    * login with above temp user
    * go to tools and reset controller
    * import backup file 
    * re-login with original user
    * scan and import recordings
    * done
for some reason I had to re-adopt the cameras though.

**Comment by coalfield** [comment] 2019-10-15 21:43
@fryfrog  is it safe to update from 3.10.6 to 3.10.8 or any of the iterations or safe to hold off for now?

**Comment by fryfrog** [comment] 2019-10-15 22:12
I'm not sure, mine has been fine the whole time. If you're running 3.10.6 and it works, you can try `:beta` which will be 3.10.10 w/ MongoDB 4.0 and see what happens. Or you could try `:testing: which should be 3.10.10 w/ the old MongoDB 3.4. It wouldn't be crazy to make a copy of your database folder, just to make things safer and easier.

**Comment by coalfield** [comment] 2019-10-20 21:41
> I'm not sure, mine has been fine the whole time. If you're running 3.10.6 and it works, you can try `:beta` which will be 3.10.10 w/ MongoDB 4.0 and see what happens. Or you could try `:testing: which should be 3.10.10 w/ the old MongoDB 3.4. It wouldn't be crazy to make a copy of your database folder, just to make things safer and easier.

I can confirm that 3.10.6 -> 3.10.8.3.4 does not work, same login issue as with the previous latest.
3.10.6 -> 3.10.8.40 does however work, after login updates firmware and working now problems.

Next test will be 3.10.10!

**Comment by 0xE1** [comment] 2019-10-22 19:34
Weirdly, I had same issue as described, though even with beta e4ddc2e I was able to create account, but not login.
On Chrome, it worked just fine on Firefox which I never used before installing e4ddc2e, though after clearing "everything" via dev console, I was able to log in.

**Comment by ddiezccg** [comment] 2019-10-24 19:54
No matter what image I used, I always got to the same login screen. This worked for me on 3.10.6

Ssh into the container:

`docker exec -it unifi-video /bin/bash`

Edit the system.properties file for unifi-video controller:

`vi /usr/lib/unifi-video/data/system.properties`

Make sure that it contains (even if it's a blank file):

`is_default=true`

That will make the controller think that it's running a setup. Before leaving the container, make sure to stop and restart the unifi-video service so that your changes are saved:

`service unifi-video stop`
`service unifi-video start`

Reload the URL and it should bring you to the setup page.

Not a permanent fix, but hope that helps.

**Comment by xboxhacks** [comment] 2019-10-25 22:36
My container got crushed after attempting to upgrade from 3.10.6 to latest tag. I've attempted to create a new container in verious versions (3.10.6, 3.10.8, 3.10.8.4.0) which fail to start also

**Comment by coalfield** [comment] 2019-10-26 08:20
> My container got crushed after attempting to upgrade from 3.10.6 to latest tag. I've attempted to create a new container in verious versions (3.10.6, 3.10.8, 3.10.8.4.0) which fail to start also

Did you remember to add the folder mappings?

**Comment by xboxhacks** [comment] 2019-10-26 12:48
> > My container got crushed after attempting to upgrade from 3.10.6 to latest tag. I've attempted to create a new container in verious versions (3.10.6, 3.10.8, 3.10.8.4.0) which fail to start also
> 
> Did you remember to add the folder mappings?

ofcourse i'm not that silly

**Comment by fryfrog** [comment] 2019-10-27 03:35
Can you guys just straight up try `:beta` from scratch? I finally fired it up in a VM and it runs me through the wizard and ends up working just fine. I stopped and started it again, still works fine.

**Comment by fryfrog** [comment] 2019-10-27 03:40
And I can again go from `:3.10.6` fresh to `:beta` no trouble.

So I've gone ahead and pushed the mongodb 4.0 to `:latest`.

**Comment by BryanWall** [comment] 2019-10-28 21:45
I installed the :beta this afternoon and restored my backup from an earlier version. All my cameras were in the "Managing" state. I had to unmanage all of them and re-add them. Once I did that, everything is working, but I am still seeing this error:

`ERROR  [uv.db.svc] Failed to acquire client connection null in MongoDb-Connecting`

I've been seeing that for the past few versions, though, and not just with the Docker container.

**Comment by coalfield** [comment] 2019-10-29 10:23
Have moved from 3.10.8.4.0 to latest and no issues found...

apart from not being able to playback timeline higher then 1x speed (although not sure if this is a new issue or was in previous versions).  Could also be something with my setup>

**Comment by jbruchanov** [comment] 2019-11-17 11:41
New installation of 3.10.10 works fine for me.
So I guess we can close this issue.

**Comment by jherman** [comment] 2019-11-17 16:04
@jbruchanov in reference to #165, that is still not the case for upgrades. Perhaps it's only working on new installations - but upgrades are broken.

**Comment by jbruchanov** [comment] 2019-11-17 17:46
@jherman 
Well, I understand that upgrade issue is not fixed.
However this ticket is about not being able to do "fresh installation for 3.10.8", 
using 3.10.10 might be the fix for this issue...

I'm not sure how the upgrade process works internally, but it feels like it should rather have own issue.

**Comment by jherman** [comment] 2019-11-17 17:48
@jbruchanov I would agree that it should have it's own case and that was why I opened #165. But #165 got closed by @fryfrog.

**Comment by evil-dog** [comment] 2019-11-18 06:50
Before seeing this issue I tried upgrading 3.10.6 straight to 3.10.10. Of course that failed with the issue of not being able to login.

I tried to roll back to 3.10.6 but continued to have the same login issue.
After that I found this thread. I tried moving to 3.10.8, but that didn't work. I was able to get the system back running using the 3.10.8.3.6 tagged image. With this image I have a fully working system again.

Since I was felling brave and knew I could get the system working again, I tried to upgrade to the 3.10.8.4.0 tag, but that failed with the same login problem.

@fryfrog, since you will probably ask for it, here is the ps aux output while running 3.10.8.3.6:
`unifi-v+   200  0.9  0.4 11727700 105028 ?     Sl   20:08   0:02 bin/mongod --config /usr/lib/unifi-video/conf mongodv3.6+.conf`

This is the ps aux output when I went back to 3.10.6 (not before trying to upgrade):
`unifi-v+   198  1.0  0.3 1123404 89316 ?       Sl   19:29   0:05 bin/mongod --config /usr/lib/unifi-video/conf mongod-wt.conf`

Is there a way to manually update the mongodb to be compatible with the -wt config?  Maybe that will help solve this problem.

**Comment by fryfrog** [comment] 2019-11-28 15:47
@evil-dog: Sorry for the late reply, but you have nailed the problem. Your db is the *old* format and that is why it works w/ 3.10.8 running mongodb 3.6. The fix is to dump your db while you're running the working version, upgrade to the not working version and load that dump into it. I did this years ago, probably google for something like "dump mongodb" or "convert mongodb wiredtiger". If I dig up the article I was looking at, I'll link it here.

**Comment by evil-dog** [comment] 2020-01-01 06:27
@fryfrog Thanks for the pointers. I used the info [here](https://docs.mongodb.com/manual/tutorial/change-standalone-wiredtiger/) to dump and restore the mongo DB.

For others looking to do the same, here is the procedure I followed:

1. Pull down the 3.10.8.3.6 tagged docker image.
2. Make sure your system is still working when you start the image up.
3. Open a bash shell into the docker image
`docker exec -it unifi-video bash`
4. Install the mongo-tools package inside of the container.
`apt install mongo-tools`
5. Find and Kill the main unifi-video service that is running as root. In my case it was PID 75.
`ps -Af`
`kill 75`
You will need to wait for the service to shutdown gracefully. Monitor using ps -Af.
6. Run mongod with the old config.
`mongod --config /usr/lib/unifi-video/conf/mongodv3.6+.conf`
7. Dump the old DB to a new directory.
`cd /var/lib/unifi-video`
`mkdir db-dump`
`mongodump --port=7441 --out=./db-dump`
8. Kill the mongod instance you started.
`pa -Af`
`kill <PID>`
9. If it already exists, delete all the files in the db-wt directory. This might exist from failed attempts to start unifi-video with WT.
10. Run mongod with WildTiger config.
`mongod --config /usr/lib/unifi-video/conf/mongod-wt.conf`
11. You will need to execute another shell into the instance as done in step 3.
12. Restore the dump into the new WT mongo DB.
`cd /var/lib/unifi-video`
`mongorestore --port=7441 db-dump/`
13. Change ownership of files in the db-wt directory.
`chown -R unifi-video:unifi-video db-wt`
14. Exit out of both shells and remove the unifi-video container.
15. Pull down the 3.10.8.4.0 tagged image.
16. Start up the new image.

At this point everything should be working. Or, at least is was for me.
You can now try updating to version 3.10.10 of unifi-video. It worked for me.

**Closed** 2020-04-04 01:58 UTC
