### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by marcofl** [pducharme/UniFi-Video-Controller#3] opened 2017-02-26 13:03 UTC
Hi, could you please also push tags to git and dockerhub? like `:3.6.1` for 3.6.1 unifi-video?

**Comment by pducharme** [comment] 2017-02-26 14:48
Not familiar with the tags, how to do that ?

**Comment by marcofl** [comment] 2017-03-07 06:27
in your clone, do `git tag v3.6.1; git push --tags` and in docker during build do `docker build . -t pducharme/UniFi-Video-Controller:3.6.1; docker push` see https://docs.docker.com/engine/reference/commandline/tag/

**Comment by fryfrog** [comment] 2017-03-28 06:36
New release, good time to try a tag maybe? :/

**Comment by fryfrog** [comment] 2017-05-17 22:03
The 3.7.0 release is out and I've pull requested it, good time to learn tags? :)

**Comment by pducharme** [comment] 2017-05-17 22:05
3.7.0 Final and not pre-release/release-candidate ?

**Comment by fryfrog** [comment] 2018-02-24 14:52
I had to downgrade from 3.9.2 to 3.9.0 and if there had been tags, I think it would have been easy. Instead, I had to build it from source. It'd be awesome if you could figure out this tagging thing! :)

**Comment by i8beef** [comment] 2018-02-24 19:42
https://docs.docker.com/docker-hub/builds/#create-an-automated-build

If I'm reading that right, just setting up that "Match versions" tag build and tagging your commits should give you the tags you want.

**Comment by i8beef** [comment] 2018-02-24 20:50
Actually, I went through some of the steps to setting up one of my own repos that are going to be Dockerized soon. It looks like, by default, an automated Docker build will follow branch names automatically for tags. So you could release branch it, and create a branch per new release you run and it'll automatically pick it up. Whether you make new BRANCHes that point at the release commit or you create new TAGS for it is up to what works for your repo.

In this case, I think if you just make a new branch called "3.9.0" and push it up, and you haven't changed anything from the defaults, Docker is gonna just pick it up. Branches will proliferate, which if you don't like that, you can instead setup the tagging strategy. Same difference.

**Comment by evil-dog** [comment] 2018-02-24 22:33
Looking at the way @jacobalberty setup his unifi repo, it appears to be a combination of branches and tags.

Looks like he has a branch tracking beta, stable candidate, and release, and then he tags the different versions in each branch.

I would try to reach out to him and see if he could provide pointers to how he has it setup and his release flow.

**Comment by jacobalberty** [comment] 2018-02-25 03:07
It's pretty simple to set it up on docker hub for automated builds (which this project appears to use). Under build settings just add  another build change type to tag, you can then leave  name and docker tag name blank and it will just use the git tag as the docker tag.

When you want to add a new tag just `git tag -a 3.6.1 -m "Version 3.6.1"` followed by `git push origin 3.6.1` sometimes i delete a tag and rebuild it (like if i updated the dockerfile to fix an issue) with `git tag -d 3.6.1`, `git push origin :3.6.1`  then make a new tag and push it back to github. I also do some fancy stuff with docker hooks to make tags on the hub that track version and git hash, you just need a hooks folder and put https://github.com/jacobalberty/unifi-docker/blob/master/hooks/post_push in it

**Comment by fryfrog** [comment] 2018-02-25 05:28
Does the Makefile in #65 look like what you'd expect to work? Trying to make it easier for @pducharme to do, but not sure how to test well.

**Comment by i8beef** [comment] 2018-02-25 05:58
@fryfrog your commit makes it a manual process with a Makefile. I don't think you need any of that. As @jacobalberty points out, there is a much easier automatic approach that "just works" with the Docker Hub stuff by setting up some branches and tagging their git commits correctly. 

Specifically I would do the following:

1. In Docker build settings, change from "master" to some other branch like "release" for the "latest" tag. This will let you mess around with master without triggering releases to docker. When you want to release a new latest, push into that branch, and Docker just handles it.
2. In Docker build settings, setup a secondary tag-based build that builds all tags of a given format (i.e., "/\d+\.\d+(\.\d+)?/" would track any tags named like "3.9" or "3.9.1", etc., and would automatically publish a new Docker tag for that commit whenever you push a new tag.
3. Now whenever you want to push a new version, push "master" to "release", to trigger the new "latest" Docker build, and push a tag onto that "release" commit of whatever the new version is (e,g,, "3.9.2"), which will trigger the "3.9.2" Docker build.

No Makefiles or manual involvement with Docker, just some Git management.

**Comment by fryfrog** [comment] 2018-02-25 06:02
Ah, that sounds way better! Get it done @pducharme! ;)

**Comment by fryfrog** [comment] 2018-02-27 01:05
@i8beef, would it be okay to name that other branch `latest`? I don't see why not, it'd go nicely w/ `beta` and of course on Dockerhub, `:latest` refers to... well, the latest one.

**Comment by fryfrog** [comment] 2018-02-27 01:34
I've created my own clone of @pducharme's Dockerhub to test with and it looks pretty simple, I made a new branch in my local checkout called `latest` from `master` and pushed it to my own repo. They haven't diverged yet. Does that sound / look right?

![screen shot 2018-02-26 at 5 31 44 pm](https://user-images.githubusercontent.com/87748/36705615-f90ed47c-1b1a-11e8-9776-970e28d62852.png)

![screen shot 2018-02-26 at 5 32 01 pm](https://user-images.githubusercontent.com/87748/36705622-fcf9e64e-1b1a-11e8-80b0-fd5df3f9cdbd.png)

So then during development, say I do it on individual branches, request a pull to the real repo, merge it to master, then when confirmed good, I just merge master -> latest and then tag the commit I want to call 3.9.3 for example?

**Comment by i8beef** [comment] 2018-02-27 01:50
Branch name is arbitrary. I tend to use "release" for mine, as it carries a logical connotation to it. When I want to release, I push to release. "Latest" in git terms is usually "master" at least on most GitHub projects. But it doesn't really matter, as long as its separate from the "master" branch so you have a dump space for merging, testing, etc. that is separate from triggering an actual release.

Your release process looks accurate to my understanding at least. Its important to note that the TAGS should be on the "latest" branch then though. You don't want to tag anything anywhere else in the repo with something that'll match your versioning tag structure, or you'll accidentally trigger a build :-)

Also, my versioning regex there was just off the top of my head. I never get regex right the first time, so check that.

**Comment by fryfrog** [comment] 2018-02-27 16:10
Great success, it works great on a test docker hub of my own pointed at my own copy of this repo! @pducharme is going to make the changes later today and we'll have tags. Yay!

**Comment by i8beef** [comment] 2018-02-27 17:37
Awesome! I needed to figure this out for my own stuff in the coming weeks, so you gave me an excuse to go figure it out :-P Thanks guys!

**Comment by fryfrog** [comment] 2018-02-27 18:07
I just pushed a 3.9.0 tag and it worked, yay. I've just merged stuff into master that I'll eventually move to release, testing that. Setup "master" to create a `testing` tag and it is working great. Neato.

**Comment by fryfrog** [comment] 2018-02-27 22:43
We're doing this! Closing issue.

**Closed by fryfrog** 2018-02-27 22:43 UTC
